### ISSUE TITLE
small simplification: src/replay_memory.py line 35, 39

### ISSUE THREAD

**Issue by mw66** [tambetm/simple_dqn#10]
35:       reward = self.min_reward

39:       reward = self.max_reward

since the comparison is done already.

**Comment by tambetm** [comment]
Actually I would prefer to move reward clipping to DeepQNetwork. Initially I put it to ReplayMemory, because I thought there is not point to do it again and again each time you sample a minibatch. But on a second thought I believe it belongs together with the network - this way you can save contents of replay memory and use some other model to learn from that. I have the fixes prepared, just testing them.
