### ISSUE TITLE
play by using backend cpu

### ISSUE THREAD

**Issue by chanhou** [tambetm/simple_dqn#2]
As the question, I am using 

./play.sh roms/pong.bin --load_weights snapshots/pong_49.pkl --backend cpu

obviously is neon problem ?

How do i solve it?

![screenshot from 2015-10-09 00 05 51](https://cloud.githubusercontent.com/assets/6903036/10372268/8fc24298-6e19-11e5-887d-285d37c533dc.png)

**Comment by tambetm** [comment]
Thanks for reporting this! It turns out, that Neon has had some changes since I did pull last time and my saved network state is not compatible with the latest Neon HEAD. I can update my saved models, but it will take few days of training. In a meantime workaround is to switch to older Neon version. My commit hash was `18863f1`, to make use of that you need to go to Neon folder and execute following commands:

```
git checkout 18863f1
make
```

I'll keep this issue updated, if I upload new models.

**Comment by tambetm** [comment]
I was wrong. Neon had introduced some changes, that required initialization of network as separate step. I added it to my code as well and now at least playing works fine with latest Neon.

**Comment by chanhou** [comment]
It works! Thanks
